### ISSUE TITLE
Feature request: Get current value

### ISSUE THREAD

**Issue by e-avalanche** [aaugustin/django-sequences#13]
This is a great package and thank you for providing it.  However, I have one feature request: what about a function to get the current value of a sequence?  Sometimes I want to see where the sequence is at (in my case so I can grab the maximum).  Thank you for your consideration.

**Comment by aaugustin** [comment]
Thanks for the feature request.

This is fairly easy to implement -- it would look like:

```python
def get_last_value(sequence_name='default', initial_value=1, *, using=None):
    connection = connections[using]
    with connection.cursor() as cursor:
        cursor.execute(SELECT, [sequence_name])
        # TODO return initial_value when the query returns no result
        last, = cursor.fetchone()
    return last
```

(+ the corresponding tests)

I'm concerned about the risk that this API will facilitate misuse of the library e.g.

```python
thing.sequence_number = get_last_value("thingies") + 1  # DON'T DO THIS!!!
```

Could you clarify your use case for "grabbing the maximum"?

If I add this API, I'd like to give good examples of how it can be used, and I'm not finding them.

**Comment by e-avalanche** [comment]
Sure, happy to!  For me, it is for versioning for compliance reasons.

I have objects, let's say `Widget`s, that store some information, let's say `name` and `value`.  While `name` remains the same, `value` changes.  For compliance reasons, I want to keep track of all old versions of `value`.

My approach is to add a third field, `version`.  Each `Widget` is immutable, and instead of updating `value`, users just create new `Widget`s with the same `name`, a difference `value` and a new `version`.  `version` is automatically tracked by sequences.

With all that background, my use case is that I want to easily get the most recent `version`.  I know that I could do something like `Widget.objects.filter(name=name).latest()`, but I am using Django Rest Framework, where a lot of pluggability requires passing a targeted *queryset* around rather than pinpointing a single object, so it would be great to doing something like:
```
Widget.objects.filter(name=name, version=get_last_value('widget_name')
```
Simply reporting the current value of a sequence is less strain on the database than aggregating over all `Widget`s with `name=name` and finding the maximum version.

Here is some code for this:
```
# models.py
from django.db import models

class Widget(models.Model):

    name = models.CharField()
    value = models.CharField()
    version = models.PositiveSmallIntegerField()

    class Meta:
        unique_together = (('name', 'version'),)

# views.py
from django.db.models import Max
from rest_framework import generics
from sequences import get_last_value
from my_app.models import Widget

class RetrieveLatestWidget(generics.RetrieveAPIView):

    # preferred
    def get_queryset(self):
        name = self.request.data['name']
        latest = get_last_value(name)
        return models.Widget.objects.filter(name=name, version=latest)

    # current
    def get_queryset(self):
        name = self.request.data['name']
        latest = Widget.objects.all().aggregate(Max('version')).values()[0]
        return models.Widget.objects.filter(name=name, version=latest)
```
From a database perspective the first is much nicer.

I don't know if this it too detailed or specific for what you like to provide, but here is a use where it would be useful!  Thank you for your consideration.

PS. I am aware of the many auditing packages, but I'd like all my objects to live together in one table to facilitate certain analyses.

**Comment by aaugustin** [comment]
This makes sense. I'll add this API.

**Comment by e-avalanche** [comment]
Excellent, thank you!

**Comment by aaugustin** [comment]
Version 2.4 is available on PyPI with this change.
