### ISSUE TITLE
django-sequences version 2.4 is not supporting

### ISSUE THREAD

**Issue by amitrathore21** [aaugustin/django-sequences#15]
django-sequences version 2.4 showing error in installed apps.
get_next_value() giving error
relation "sequences_sequence" does not exist
LINE 2:     INSERT INTO sequences_sequence (name, last)

**Comment by aaugustin** [comment]
You didn't run `django-admin migrate`. Please double check the installation instructions.

**Comment by amitrathore21** [comment]
Is it necessary to have a app name sequences.i created a app with app name
org_sequences and model is sequence.so when I am running the
get_next_value() it is trying to find the relation sequences_sequence.and
couldn't get it.

**Comment by aaugustin** [comment]
Can you clarify what you mean by "i created a app with app name
org_sequences"?

Did you re-label the app with a custom `AppConfig` class that sets the [label](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig.label) to `"org_sequences"`?

**Comment by amitrathore21** [comment]
Inside my project I started app
With this command
Python manage.py startapp org_sequences

**Comment by aaugustin** [comment]
And then you copy-pasted django-sequences inside that app?

**Comment by aaugustin** [comment]
#16 should fix your issue anyway.

**Comment by amitrathore21** [comment]
Yes, according to my app setup db created with a new relation which is
org_sequences_sequence where org_sequence is app name and sequence is a
model. But while implenting get_next_value() function it is giving me error
like feld to insert.no realtion sequences_sequence.

**Comment by amitrathore21** [comment]
while running django-admin migrate
django.core.exceptions.ImproperlyConfigured: Requested setting
INSTALLED_APPS, but settings are not configured. You must either define the
environment variable DJANGO_SETTINGS_MODULE or call settings.configure()
before accessing settings.can you pls help me with this.

**Comment by aaugustin** [comment]
I can't help. If you want help, you need to explain accurately each step you're taking and what  result you're getting.

You didn't show any of your code. I don't know how you installed django-sequences. I don't know if you applied changes in #16.

The ImproperlyConfigured error is unrelated to django-sequnces.

Let's leave it there.
