### ISSUE TITLE
Help elaborate the background of the problem? 

### ISSUE THREAD

**Issue by anzharip** [aaugustin/django-sequences#20]
Hi, this is a great extension and I love it. Just want to ask though: 
```
If a transaction inserts a row and then is rolled back, the sequence counter isn't rolled back for performance reasons, creating a gap in primary keys.

This can cause compliance issues for some use cases such as accounting.

This risk isn't well known. Since most transactions succeed, values look sequential. Gaps will only be revealed by audits. 
```

Is this only applies to PostgreSQL or it applies to Django with any DB backend in general?

Thanks!

**Comment by oonid** [comment]
hi,
MySQL also has that kind of behavior.
take a look at [this answer on StackOverflow](https://stackoverflow.com/questions/2787910/why-does-mysql-autoincrement-increase-on-failed-inserts).

**Comment by anzharip** [comment]
Hi @oonid, thanks for chiming in! I read through the StackOverflow thread, and it surely is a useful insight (at least for me, I just discovered this). 

Also, another discussion on similar behaviour on [PostgreSQL](https://stackoverflow.com/questions/53642512/sequential-increment-skipping-numbers) and [SQL Server](https://stackoverflow.com/questions/30276076/why-does-my-auto-incremented-id-skip-numbers-in-sql-server). 

Also, what I have in mind is to add references to similar discussion to improve the readme.

**Comment by aaugustin** [comment]
Oracle also has this behavior.

Among the built-in database backends, only SQLite doesn't.

**Comment by aaugustin** [comment]
It's worth adding some links to the README.

I'm just unsure about mentioning SQL Server (documentation : https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15#remarks) as I never tested django-sequences on SQL Server.

**Comment by anzharip** [comment]
@aaugustin yep. Maybe for a starter we can add notes on [Django's officially supported DB](https://docs.djangoproject.com/en/3.0/ref/databases/)? 

```
Django officially supports the following databases:

PostgreSQL
MariaDB
MySQL
Oracle
SQLite
```
