### ISSUE TITLE
Document usage with different isolation levels

### ISSUE THREAD

**Issue by PetrDlouhy** [aaugustin/django-sequences#22]
I was getting `OperationalError: could not serialize access due to concurrent update` when I was testing two concurrent requests with `django-sequences`. Now I realized, that I get those only if I have set `'isolation_level': ISOLATION_LEVEL_REPEATABLE_READ`.

I would appreciate, if usage of `django-sequences` with different isolation levels was discussed in the documentation.

**Comment by aaugustin** [comment]
Yes, it would be interesting — at least, for someone with this kind of peculiar interests ;-) — to run the tests with all isolation levels, see what happens, and document it.

Perhaps even better: modify the test suite to run with all supported isolation levels.

**Comment by aaugustin** [comment]
https://www.postgresql.org/docs/current/transaction-iso.html says:

> Applications using this level must be prepared to retry transactions due to serialization failures.

Were you prepared? ;-)

**Comment by aaugustin** [comment]
So, yeah, interesting investigation :-)

There's too much difference in behavior across databases at isolation levels other than read committed so I gave up testing these scenarios.
