### ISSUE TITLE
About daily sequence 

### ISSUE THREAD

**Issue by hc2021hc** [aaugustin/django-sequences#31]
Hello, I would like to generate a sequence which renews everyday.  Is there any function to do so?
e.g. yyyymmddNN. where NN will start from 01 for each date.  Thanks.

**Comment by adamchainz** [comment]
This should work:

```python
from datetime import date
from sequences import get_next_value
get_next_value(f"books-{date.today().isoformat()}")
```

**Comment by hc2021hc** [comment]
Sorry I'm new to Python.  I would like to ask how I can fallback to previous value if some transaction fails?

say, with transaction.atomic():   
      get next seq value()
      doing sth
      save to database

For example, if get_next_value is 2 and save to database fails, I hope the seq can be reverted to 1, how can it be achieved?

**Comment by adamchainz** [comment]
That should already happen - as the README says:

>  if the transaction is rolled back, the generated value isn't consumed.

**Comment by spapas** [comment]
Hey, this is very useful, please put it in the README! 

I need a sequence of the form `number / year` (which will reset each year) and it solves my problem just fine

**Comment by adamchainz** [comment]
Sure, we could do that, would you like to prepare a PR @spapas ?

**Comment by aaugustin** [comment]
Indeed, we could add an "Examples" section after "API" and before "Database support".

**Comment by spapas** [comment]
Hey friends, I've submitted PR #35 with the examples section.

Kind regards,
Serafeim
