### ISSUE TITLE
PositiveBigIntegerField 

### ISSUE THREAD

**Issue by petrprikryl** [aaugustin/django-sequences#32]
Hi, thanks for great package. I would like to ask if it would be possible to change `PositiveIntegerField` to `PositiveBigIntegerField`? Because I have sequence where 2147483647 number is too small.

https://github.com/aaugustin/django-sequences/blob/d58f4e6fab4fcbc70ffe1e73e8a9db9ed694c88d/src/sequences/models.py#L13

**Comment by aaugustin** [comment]
Argh, this is going to involve the same kind of logistics as when Django changed PK from Integer to BigInteger. Makes sense, but I can't just change it outright, for backwards compatibility reasons.

**Comment by petrprikryl** [comment]
I think that it should be very easy as the field is not PK. And the table will have only few entries in most cases. So compatibility should be ensured. Am I missing something? You could make new major release to be sure about making this change? :slightly_smiling_face:

**Comment by adamchainz** [comment]
I agree it shouldn't be too disruptive since it's not the PK. I don't know what else would need changing apart from the migration.

> and the table will have only few entries in most cases.

I think it's reasonable to believe there are deployments with 100k or millions of sequences. It's reasonable to create one sequence per user/project/etc. That said I think it's probably fine to include a migration and a changelog note about it.

**Comment by aaugustin** [comment]
You're right. It's not that complicated if we just ship a migration for all users. Let's do that.

I've been considering whether we could provide a setting controlling this. Unfortunately, the interaction between the value of this setting and the existence of the migration gets messy really quickly. It isn't worth the effort.

If someone doesn't want the migration and only have small sequences, they can just `migrate --fake`.

**Comment by aaugustin** [comment]
So the expected change here is:

- change field type
- generate migration
- explain things in changelog

**Comment by aaugustin** [comment]
Fixed in #33.
