### ISSUE TITLE
Separate sequence property specifiers

### ISSUE THREAD

**Issue by alfawal** [aaugustin/django-sequences#36]
When using
```py
get_next_value("orders", initial_value=100, reset_value=500)
```
I can easily tell what this function does and what values to expect, but if this sequence name was used in multiple files as
```py
get_next_value("orders")
```
it wouldn't be obvious or it would be hard to figure out what the `initial_value` or the `rest_value` is.

My proposal is doing one of:

1. allowing a declarative class usage:
```py
orders_sequence = DjangoSequence("orders", initial_value=100, reset_value=500)

get_next_value(orders_sequence)
```

2. enum-like usage:
```py
class DjangoSequences:
    ORDERS = DjangoSequence("orders", initial_value=100, reset_value=500)

get_next_value(DjangoSequences.ORDERS)
```

My current usage is like the following:
```py
orders_sequence = {"sequence_name": "orders", "initial_value": 100, "reset_value": 500}

get_next_value(**orders_sequence)
```

**Comment by aaugustin** [comment]
Search for "object-oriented API" in the README. I believe that it does what you want. If not, could you clarify why it doesn't?

**Comment by alfawal** [comment]
Yes this is what I was looking for, I thought it was something else. I will give it a try. Thanks a lot.
