### ISSUE TITLE
dropping old sequences

### ISSUE THREAD

**Issue by fledman** [aaugustin/django-sequences#37]
Currently to drop outdated/unwanted sequences from the database, you need to use the private api.
(eg via orm operations on `sequences.models.Sequence`)

It would be nice if this functionality was exposed in the public api.

**Comment by aaugustin** [comment]
Fair point.

Right now you can delete them from the admin. But that may be inconvenient if you have lots of sequences ;-)

**Comment by aaugustin** [comment]
What do you think o #38?

**Comment by fledman** [comment]
looks good to me

**Comment by fledman** [comment]
Although if you are adding things, a function to list all active sequence names would be useful.
