### ISSUE TITLE
Expand get_next_value for multiple sequences

### ISSUE THREAD

**Issue by bverhoeve** [aaugustin/django-sequences#39]
Hi, we are using `django-sequences` to generate gapless sequence numbers for objects. In some requests we'll create multiple objects in the same sequence, which will all get a sequence value. Currently, we have to call `get_next_value()` multiple times, as the increment is hard-coded in the upsert query. This leads to an effective N+1 problem, which can harm performance in case of many sequenced objects.

I'd suggest expanding on `get_next_value()` with a `get_next_values()` that allows you to retrieve multiple sequences to distribute in a single query. Happy to create a PR for this as well.

**Comment by aaugustin** [comment]
Thank you for the suggestion. What do you think of #40? Would you be able to test it and confirm that it does what you want?

**Comment by aaugustin** [comment]
I'm going to try implementing the API you suggested instead of just adding a parameter. I think it will look nicer.

**Comment by aaugustin** [comment]
What do you think of #41? Would you be able to test it and confirm that it does what you want?

**Comment by bverhoeve** [comment]
Hi, apologies I was on a holiday 🙃 Thanks for the quick reply, will check!

**Comment by bverhoeve** [comment]
Great stuff! Looks exactly like what we'd need 😄 I've tested it in our system as well and it would integrate well.

**Comment by aaugustin** [comment]
Version 3.0 is available on PyPI with this feature.
