### ISSUE TITLE
Not support for python 2?

### ISSUE THREAD

**Issue by kevin8909** [aaugustin/django-sequences#4]
When using it in python2.7 enviroment. met this problem:
`File "/usr/local/lib/python2.7/dist-packages/sequences/__init__.py", line 6
    *, nowait=False, using=None):
     ^
SyntaxError: invalid syntax`

**Comment by aaugustin** [comment]
Yeah, I'm using keyword-only arguments to make sure my libs only run on Python 3. That's for your own good.

The code probably works on Python 2 if you remove the offending `*`.
